### ISSUE TITLE
NPE captured in MorphiaService.releaseResources

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-morphia#31]
```
java.lang.NullPointerException: null
        at act.db.morphia.MorphiaService.releaseResources(MorphiaService.java:144)
        at act.util.LogSupportedDestroyableBase.destroy(LogSupportedDestroyableBase.java:50)
        at act.Destroyable$Util.tryDestroyAll(Destroyable.java:95)
        at act.app.DbServiceManager.releaseResources(DbServiceManager.java:165)
        at act.util.LogSupportedDestroyableBase.destroy(LogSupportedDestroyableBase.java:50)
        at act.Destroyable$Util.destroyAll(Destroyable.java:59)
        at act.app.AppServiceRegistry.destroy(AppServiceRegistry.java:84)
        at act.app.App.clearServiceResourceManager(App.java:1390)
        at act.app.App.releaseResources(App.java:586)
        at act.util.LogSupportedDestroyableBase.destroy(LogSupportedDestroyableBase.java:50)
```

**Comment by greenlaw110** [comment]
Fixed in commit 6f58313
